language: python
python:
  - "3.2"
  - "3.3"
notifications:
  email: false
install: pip install http://nltk.org/nltk3-alpha/nltk-3.0a3.tar.gz && wget http://dl.dropboxusercontent.com/u/90405495/resources.zip && unzip resources.zip -d resources
script: export JAVAHOME=/usr/bin/java && python tests.py
