language: python
python:
  - "3.3"
notifications:
  email: false
install: git clone https://github.com/nltk/nltk/ && cd nltk && python setup.py install && cd ..
script: python -m hazm.Normalizer && python -m hazm.SentenceTokenizer && python -m hazm.WordTokenizer && python -m hazm.Stemmer && python -m hazm.Lemmatizer
