name: Format code

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install black formatter
      run: pip install black
        
    - name: Format all codes with black formatter
      run: black .
      
    - name: Format docstrings with a custom formatter
      run: python format_docstrings.py
        
    - name: Push back changes          
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Refactor code based on pep-8"
        commit_user_name: "formatter-bot"
        commit_user_email: "formatter-bot@users.noreply.github.com"
