name: Run lints
on:    
    push:        
        paths: ["**.py"]    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout master
          uses: actions/checkout@v3
          
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v35
          with:
            files: |
              **/*.py
          
        - name: Upgrade pip
          run: pip install --upgrade pip
          
        - name: Install ruff
          run: pip install ruff
          
        - name: Ruff check          
          run: ruff check ${{ steps.changed-files.outputs.all_changed_files }}
