name: Run lints
on:
    workflow_dispatch:
    push:
        branches: [master]
        paths: ["**.py", "hazm/**", "corpora/**"]
    pull_request:
        branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout master
          uses: actions/checkout@v3

        - name: Install and configure Poetry
          uses: snok/install-poetry@v1

        - name: Install dependencies
          run: |
            poetry lock
            poetry install --only dev        

        - name: Run lints
          run: poetry poe lint --format github
