name: Run lints
on:
    workflow_dispatch:
    push:
        branches: [master]
        paths: ["**.py", "hazm/**", "corpora/**"]
    pull_request:
        branches: [master]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        
      - name: Ruff check --fix
        uses: chartboost/ruff-action@v1
