name: Run lints
on:
    workflow_dispatch:
    push:
        branches: [master]
        paths: ["**.py", "hazm/**", "corpora/**"]
    pull_request:
        branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout master
          uses: actions/checkout@v3

        - name: Install Python
          uses: actions/setup-python@v4
          
        - name: Install ruff
          run: pip install ruff

        - name: Run lints
          run: ruff check . --format github
