name: Close old issues

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Close old issues that need reply
        uses: dwieeb/needs-reply@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: needs-reply
          days-before-close: 180
          close-message: "باتوجه به اینکه پیگیری این ایشو نیازمند ارائه اطلاعات بیشتر است و هنوز بعد از گذشت ۶ ماه، پاسخی به آن دریافت نشده، به صورت خودکار بسته می‌شود."
