name: Close old issues that need reply

on:
  schedule:
    - cron: "0 0 0 * *" # Run 00:00 every month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Close old issues that need reply
        uses: dwieeb/needs-reply@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: needs-reply
          days-before-close: 180
          close-message: "این ایشو از آنجایی که پیگیری آن نیازمند ارائه اطلاعات بیشتر بوده و ۳۰ روز است که به آن پاسخی داده نشده، به صورت خودکار بسته می‌شود."
