name: Publish to pypi

on: 
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:        
        virtualenvs-create: false
        virtualenvs-in-project: false           
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{secrets.PYPITEST_TOKEN}}
          poetry publish --build -r test-pypi
          
      
    
      
