name: Publish to test.pypi.org

on: 
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:        
        virtualenvs-create: false
        virtualenvs-in-project: false
    - name: Publish to test.pypi.org
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{secrets.TESTPYPI_TOKEN}}
        poetry publish --build -r testpypi
          
      
    
      
