name: Publish to pypi

on: 
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Build and publish
      run: |
        poetry config pypi-token.test-pypi ${{secrets.TESTPYPI_TOKEN}}
        poetry publish --build -r test-pypi
        # poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}               
        # poetry publish --build
    
      
