name: Publish to pypi

on: 
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Build and publish to test.pypi.org
      uses: JRubics/poetry-publish@v1.16
      with:
        pypi_token: ${{ secrets.TESTPYPI_TOKEN }}        
        repository_url: "https://test.pypi.org/legacy/"
    
      
