on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'hazm/**'
      - 'corpora/**'
  workflow_run:
    workflows: ["Format code"]
    types:
      -completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(steps.python-versions.outputs.python-version-matrix) }}
        include:
          - python-version: 2.7
        exclude:
          - python-version: 2.7
          - python-version: 3.11
          
    steps:
    - uses: actions/checkout@v3
    - name: Get latest Python versions
      id: python-versions
      uses: actions/python-versions@v1
      with:
        releases-type: stable # optional, defaults to stable
        include-prereleases: false # optional, defaults to false
        major-versions-count: 5 # optional, defaults to 3

    - name: Set up matrix for Python versions
      run: echo "::set-output name=matrix::${{ join(fromJson(steps.python-versions.outputs.python-version-matrix) | select(. != '3.11'), ',') }}, 2.7"
      #run: echo "::set-output name=matrix::${{ join(fromJson(steps.python-versions.outputs.python-version-matrix) }}, 2.7"
      id: set-matrix 
    
    - name: Run tests  
      uses: actions/setup-python@v4
      with:
        python-version: ${{ fromJson(steps.set-matrix.outputs.matrix) }}
        
    - name: Install prerequisites
      run: |
        pip install .
        wget https://github.com/sobhe/hazm/releases/download/v0.5/resources-0.5.zip
        wget https://github.com/sobhe/hazm/releases/download/v0.5/resources-stanford.zip
        unzip resources-0.5.zip -d resources
        unzip resources-stanford.zip -d resources
        
    - name: Run tests
      run: python tests.py
