on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'hazm/**'
      - 'corpora/**'
  workflow_run:
    workflows: ["Format code"]
    types:
      -completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ steps.python_versions.outputs.python_versions }}
        include:
          - python-version: '2.7'
        exclude:
          - python-version: '2.7'
          - python-version: '3.11'
          
    steps:
    - uses: actions/checkout@v3
    - name: Get latest Python versions
      id: python_versions
      uses: jwodder/latest-python-versions@v1
      with:
        count: 5
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}
        
    - name: Install prerequisites
      run: |
        pip install .
        wget https://github.com/sobhe/hazm/releases/download/v0.5/resources-0.5.zip
        wget https://github.com/sobhe/hazm/releases/download/v0.5/resources-stanford.zip
        unzip resources-0.5.zip -d resources
        unzip resources-stanford.zip -d resources
        
    - name: Run tests
      run: python tests.py
