name: Run tests

on:
    workflow_dispatch:
    push:
        branches: [master]
        paths: ["**.py", "hazm/**", "corpora/**"]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                python-versions: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - name: Checkout master
              uses: actions/checkout@v3

            - name: Install Python ${{ matrix.python-versions }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-versions }}

            - name: Install poetry
              run: curl -sSL https://install.python-poetry.org | python3 -

            - name: Install dependencies
              run: |
                poetry lock
                poetry install --with dev            

            - name: Download resources
              run: |
                  mkdir resources
                  wget -P /resources https://download1488.mediafire.com/f9dh0pxekptgNUY_U1Xu5g7p8a153EfPZkuTPGj6ov6yEe187_A4eJI3kOU5AKMGQYmLerkeCYS4HSnqj9Gg2YmIUuHi2sOD-id1et79FctWCigkqar-y0i1S1a2mcpwOZtl0VznQAfWkNjLoYILYT4WSBSeVquRZ7_ctrQ624aQJg/963bufx117w5aan/cc.fa.300.bin
                  wget -P /resources https://download843.mediafire.com/urcyz5l2ldygsHOfz_sMhpQ2vTcnhnVCxiyuCYbDm4z50JMTCD4u4puAQWC7nV5oxZrcojDeoZrxoCdmmvzOXv2Bl7Kup0lHRFuMS7D_I9S8TyuYJdRN-cS5exAAMlHO9YCm-h7T64M-CyTCsG0_0TPZQZdkrxbkzt1da5O7OEI_Ew/nvea42k6epj5rn0/chunker.model
                  wget -P /resources https://download1530.mediafire.com/uod84bh0l4vgvmWtDWxQobnfZJ4CCRFZ2GMNPTDD7pRjMO-9yoxupW1L6e8VOdMe1-kFyOfnytFXnX_3i7gF43Xr8TYfsXroNfsJe3iM7Iv6eFOr30oU-R63i4h2e_nnltGKX7OdjurMAAH280vXWsdtpz2sO9WPEYZEW6gIHA0Ipg/zm1jufrj8dqg6up/langModel.mco
                  wget -P /resources https://download1502.mediafire.com/51chka1iyrvg-QrNBVpVFgg3MpHpF-fy7xnsnAHLxuo7g1wTB_VdSXmQM1TgVtHCZCpyQ42bHs10k_eUSQOmRHQC16i3rhmzX38rb78vug4C6uDl4OdZRGdkipRtDW3ldC3OYT9A2t6wOqZ-GaIdVINgfVF9yzt2zZF3nXXdpRjA4A/62u1lchxnqcjiar/malt.jar
                  wget -P /resources https://download1527.mediafire.com/j34t8bhmh74grz0jivHJpHZb-RWWOX3hoqcfUitbB3XxtONq4mFb4YtGWFB5CZMC0H4u0IIOhk5TFFgkzkTde3rx_LP1uxmVXufcGOY97vy-BZkDbWS8IgiiLD_nRvh6QDQ8osbwfBDEQeZPdj8f6nsT7zMF1uD2rPlJHzDkz6T7gg/pfyxwi0s2qazevj/pos_tagger.model
                  wget -P /resources https://download1476.mediafire.com/0no6k0c79shgqi3FNyl9QMpKbEi2YQfjqaSxHeQgIA8sQmyPelN_Y0kYTHHMv9ias3ZR6m8VG_Ox7SDwNW1cqi5UPyZAo-zgCiHW6gNUvGiXriFHmJQKyNtBtrBEbkMdxpqYMWzvrc27Q9KjvZ6opWW9M36TC5mHlfb0nO3MtcMeTQ/92sxwznb4460al3/sent2vec.model
                  wget -P /resources https://download1514.mediafire.com/bqzoxzsna4ugmanXpQUDJr8Syn5EwlH630ix8M9ivpwJvXODNyCJR_sW-tlZEvf9o8mc_IC3YfPbKXRAMYXKSI9HsGlHw02DJdveKou-sxloLa1A4uBuSPQF7Wv1bm4JsznBb69XNwZROD04OLSk4ZDNYjcTVpLLuFYUiVI86H45Yg/o6qzqccxfh3sv9j/stanford_postagger.jar

            - name: Run tests
              run: poetry run poe test
