name: Run tests

on:
    workflow_dispatch:
    push:
        branches: [master]
        paths: ["**.py", "hazm/**", "corpora/**"]
    pull_request:
        branches: [master]
    workflow_run:
        workflows: ["Format code"]
        types: [completed]

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                python-versions: ["3.11"] 
                #python-versions: ["3.7", "3.8", "3.9", "3.10", "3.11"]                

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-versions }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-versions }}
                  
            - name: Install and configure Poetry
              run: curl -sSL https://install.python-poetry.org | python3 -
              
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: false
                virtualenvs-in-project: false
                
            - name: Install requirements packages            
              run: |                
                poetry lock                
                poetry install                
                  
            - name: Install poethepoet
              run: pip install poethepoet 

            - name: Download resources
              run: |                                   
                  wget https://github.com/sir-kokabi/test/raw/main/resources-0.9.zip            
                  unzip resources-0.9.zip -d resources          

            - name: Run tests
              run: poe test
